# Generated by Django 3.1.5 on 2021-01-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sort', models.IntegerField(verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ads.category', verbose_name='Родительская категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
