# Generated by Django 3.1.5 on 2021-01-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название региона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL([
            "INSERT INTO ads_region (id, name, created_at, updated_at) VALUES \
            (1,	'Республика Адыгея (Адыгея)', current_timestamp, current_timestamp), \
            (2,	'Республика Башкортостан', current_timestamp, current_timestamp), \
            (3,	'Республика Бурятия', current_timestamp, current_timestamp), \
            (4,	'Республика Алтай', current_timestamp, current_timestamp), \
            (5,	'Республика Дагестан', current_timestamp, current_timestamp), \
            (6,	'Республика Ингушетия', current_timestamp, current_timestamp), \
            (7,	'Кабардино-Балкарская Республика', current_timestamp, current_timestamp), \
            (8,	'Республика Калмыкия', current_timestamp, current_timestamp), \
            (9,	'Карачаево-Черкесская Республика', current_timestamp, current_timestamp), \
            (10,	'Республика Карелия', current_timestamp, current_timestamp), \
            (11,	'Республика Коми', current_timestamp, current_timestamp), \
            (12,	'Республика Марий Эл', current_timestamp, current_timestamp), \
            (13,	'Республика Мордовия', current_timestamp, current_timestamp), \
            (14,	'Республика Саха (Якутия)', current_timestamp, current_timestamp), \
            (15,	'Республика Северная Осетия — Алания', current_timestamp, current_timestamp), \
            (16,	'Республика Татарстан (Татарстан)', current_timestamp, current_timestamp), \
            (17,	'Республика Тыва', current_timestamp, current_timestamp), \
            (18,	'Удмуртская Республика', current_timestamp, current_timestamp), \
            (19,	'Республика Хакасия', current_timestamp, current_timestamp), \
            (20,	'Чеченская Республика', current_timestamp, current_timestamp), \
            (21,	'Чувашская Республика — Чувашия', current_timestamp, current_timestamp), \
            (22,	'Алтайский край', current_timestamp, current_timestamp), \
            (23,	'Краснодарский край', current_timestamp, current_timestamp), \
            (24,	'Красноярский край', current_timestamp, current_timestamp), \
            (25,	'Приморский край', current_timestamp, current_timestamp), \
            (26,	'Ставропольский край', current_timestamp, current_timestamp), \
            (27,	'Хабаровский край', current_timestamp, current_timestamp), \
            (28,	'Амурская область', current_timestamp, current_timestamp), \
            (29,	'Архангельская область', current_timestamp, current_timestamp), \
            (30,	'Астраханская область', current_timestamp, current_timestamp), \
            (31,	'Белгородская область', current_timestamp, current_timestamp), \
            (32,	'Брянская область', current_timestamp, current_timestamp), \
            (33,	'Владимирская область', current_timestamp, current_timestamp), \
            (34,	'Волгоградская область', current_timestamp, current_timestamp), \
            (35,	'Вологодская область', current_timestamp, current_timestamp), \
            (36,	'Воронежская область', current_timestamp, current_timestamp), \
            (37,	'Ивановская область', current_timestamp, current_timestamp), \
            (38,	'Иркутская область', current_timestamp, current_timestamp), \
            (39,	'Калининградская область', current_timestamp, current_timestamp), \
            (40,	'Калужская область', current_timestamp, current_timestamp), \
            (41,	'Камчатский край', current_timestamp, current_timestamp), \
            (42,	'Кемеровская область', current_timestamp, current_timestamp), \
            (43,	'Кировская область', current_timestamp, current_timestamp), \
            (44,	'Костромская область', current_timestamp, current_timestamp), \
            (45,	'Курганская область', current_timestamp, current_timestamp), \
            (46,	'Курская область', current_timestamp, current_timestamp), \
            (47,	'Ленинградская область', current_timestamp, current_timestamp), \
            (48,	'Липецкая область', current_timestamp, current_timestamp), \
            (49,	'Магаданская область', current_timestamp, current_timestamp), \
            (50,	'Московская область', current_timestamp, current_timestamp), \
            (51,	'Мурманская область', current_timestamp, current_timestamp), \
            (52,	'Нижегородская область', current_timestamp, current_timestamp), \
            (53,	'Новгородская область', current_timestamp, current_timestamp), \
            (54,	'Новосибирская область', current_timestamp, current_timestamp), \
            (55,	'Омская область', current_timestamp, current_timestamp), \
            (56,	'Оренбургская область', current_timestamp, current_timestamp), \
            (57,	'Орловская область', current_timestamp, current_timestamp), \
            (58,	'Пензенская область', current_timestamp, current_timestamp), \
            (59,	'Пермский край', current_timestamp, current_timestamp), \
            (60,	'Псковская область', current_timestamp, current_timestamp), \
            (61,	'Ростовская область', current_timestamp, current_timestamp), \
            (62,	'Рязанская область', current_timestamp, current_timestamp), \
            (63,	'Самарская область', current_timestamp, current_timestamp), \
            (64,	'Саратовская область', current_timestamp, current_timestamp), \
            (65,	'Сахалинская область', current_timestamp, current_timestamp), \
            (66,	'Свердловская область', current_timestamp, current_timestamp), \
            (67,	'Смоленская область', current_timestamp, current_timestamp), \
            (68,	'Тамбовская область', current_timestamp, current_timestamp), \
            (69,	'Тверская область', current_timestamp, current_timestamp), \
            (70,	'Томская область', current_timestamp, current_timestamp), \
            (71,	'Тульская область', current_timestamp, current_timestamp), \
            (72,	'Тюменская область', current_timestamp, current_timestamp), \
            (73,	'Ульяновская область', current_timestamp, current_timestamp), \
            (74,	'Челябинская область', current_timestamp, current_timestamp), \
            (75,	'Забайкальский край', current_timestamp, current_timestamp), \
            (76,	'Ярославская область', current_timestamp, current_timestamp), \
            (77,	'Город Москва', current_timestamp, current_timestamp), \
            (78,	'Санкт-Петербург', current_timestamp, current_timestamp), \
            (79,	'Еврейская автономная область', current_timestamp, current_timestamp), \
            (83,	'Ненецкий автономный округ', current_timestamp, current_timestamp), \
            (86,	'Ханты-Мансийский автономный округ — Югра', current_timestamp, current_timestamp), \
            (87,	'Чукотский автономный округ', current_timestamp, current_timestamp), \
            (89,	'Ямало-Ненецкий автономный округ', current_timestamp, current_timestamp);",
        ]),
    ]
