# Generated by Django 3.1.5 on 2021-01-10 20:27

from django.db import migrations


def add_categories(apps, schema_editor):
    """Создание категорий."""

    categories_data = [
        {
            'id': 1,
            'name': 'Транспорт',
            'slug': 'transport',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 2,
            'name': 'Автомобили',
            'slug': 'avtomobili',
            'sort': 1,
            'parent': 1,
        },
        {
            'id': 3,
            'name': 'Мотоциклы и мототехника',
            'slug': 'mototsikly-i-mototekhnika',
            'sort': 1,
            'parent': 1,
        },
        {
            'id': 4,
            'name': 'Грузовики и спецтехника',
            'slug': 'gruzoviki-i-spetstekhnika',
            'sort': 1,
            'parent': 1,
        },
        {
            'id': 5,
            'name': 'Водный транспорт',
            'slug': 'vodnyy-transport',
            'sort': 1,
            'parent': 1,
        },
        {
            'id': 6,
            'name': 'Запчасти и аксессуары',
            'slug': 'zapchasti-i-aksessuary',
            'sort': 1,
            'parent': 1,
        },
        {
            'id': 7,
            'name': 'С пробегом',
            'slug': 's-probegom',
            'sort': 1,
            'parent': 2,
        },
        {
            'id': 8,
            'name': 'Новый',
            'slug': 'noviy',
            'sort': 1,
            'parent': 2,
        },
        {
            'id': 9,
            'name': 'Багги',
            'slug': 'baggi',
            'sort': 1,
            'parent': 3,
        },
        {
            'id': 10,
            'name': 'Мотоциклы',
            'slug': 'mototsikly',
            'sort': 1,
            'parent': 3,
        },
        {
            'id': 11,
            'name': 'Мопеды и скутеры',
            'slug': 'mopedy-i-skutery',
            'sort': 1,
            'parent': 3,
        },
        {
            'id': 12,
            'name': 'Недвижимость',
            'slug': 'nedvizhimost',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 13,
            'name': 'Квартиры',
            'slug': 'kvartiry',
            'sort': 1,
            'parent': 12,
        },
        {
            'id': 14,
            'name': 'Комнаты',
            'slug': 'komnaty',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 15,
            'name': 'Услуги',
            'slug': 'uslugi',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 16,
            'name': 'Личные вещи',
            'slug': 'lichnyye-veshchi',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 17,
            'name': 'Для дома и дачи',
            'slug': 'dlya-doma-i-dachi',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 18,
            'name': 'Бытовая электроника',
            'slug': 'bytovaya-elektronika',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 19,
            'name': 'Хобби и отдых',
            'slug': 'khobbi-i-otdykh',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 20,
            'name': 'Животные',
            'slug': 'zhivotnyye',
            'sort': 1,
            'parent': None,
        },
        {
            'id': 21,
            'name': 'Готовый бизнес и оборудование',
            'slug': 'gotovyy-biznes-i-oborudovaniye',
            'sort': 1,
            'parent': None,
        },
    ]
    Category = apps.get_model('ads', 'Category')
    for category_data in categories_data:
        parent = Category.objects.get(pk=category_data['parent']) \
            if category_data['parent'] is not None else None
        category_data['parent'] = parent
        Category.objects.update_or_create(
            slug=category_data['slug'], defaults=category_data)


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_moderationentry'),
    ]

    operations = [
        migrations.RunPython(add_categories, reverse_code=migrations.RunPython.noop),
    ]
